import cv2
import numpy as np
image= cv2.imread("D:/watch.jpg")
retval,threshold = cv2.threshold(image,150,255,cv2.THRESH_BINARY)
grayscaled =cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
kernel=np.ones((5,5),np.float32)/25
dst = cv2.filter2D(image,-1,kernel)
blur= cv2.blur(image,(5,5))
laplacian = cv2.Laplacian(grayscaled,cv2.CV_64F)
#retval2,threshold2= cv2.threshold(grayscaled,150,255,cv2.THRESH_BINARY)
#gaus = cv2.adaptiveThreshold(grayscaled,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,115,1)
#gaus1 = cv2.adaptiveThreshold(grayscaled,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,11,2)
#gaus2 = cv2.adaptiveThreshold(grayscaled,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,11,1)
#retval,otsu = cv2.threshold(grayscaled,0,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
cv2.imshow('image',image)
#cv2.imshow('threshold1',threshold)
#cv2.imshow('threshold2',threshold2)
#cv2.imshow('thresholdgauss',gaus)
#cv2.imshow('thresholdgauss1',gaus1)
#cv2.imshow('thresholdgauss2',gaus2)
#cv2.imshow('blur1',blur)
#cv2.imshow('blur',dst)
#cv2.imshow('otsu binarization',otsu)
cv2.imshow('laplacian',laplacian)
cv2.waitKey(0)
cv2.destroyAllWindows()
